name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/designs/images/auto-group-tnaw.png
    - assets/designs/images/background-primary-bg.png
    - assets/designs/images/group-6.png
    - assets/designs/images/auto-group-aqrh.png
    - assets/designs/images/frame-4.png
    - assets/designs/images/auto-group-bzoy.png
    - assets/designs/images/auto-group-kh31.png
    - assets/designs/images/icon-plus-circle.png
    - assets/designs/images/combined-shape.png
    - assets/designs/images/background-primary-bg-GiL.png
    - assets/designs/images/background-primary-bg-Cnt.png
    - assets/designs/images/background-primary-bg-tLp.png
    - assets/designs/images/delete.png
    - assets/designs/images/battery.png
    - assets/designs/images/user-1-1.png
    - assets/designs/images/pants2.png
    - assets/designs/images/combined-shape-XNG.png
    - assets/designs/images/.png
    - assets/designs/images/color.png
    - assets/designs/images/group-11.png
    - assets/designs/images/ellipse-8.png
    - assets/designs/images/wallet-1.png
    - assets/designs/images/combined-shape-M5S.png
    - assets/designs/images/group-19.png
    - assets/designs/images/icon-chevron-left.png
    - assets/designs/images/battery-hyA.png
    - assets/designs/images/bx-sort-1.png
    - assets/designs/images/auto-group-cmoz.png
    - assets/designs/images/frame-7.png
    - assets/designs/images/shoes.png
    - assets/designs/images/auto-group-b8mh.png
    - assets/designs/images/auto-group-5vsj.png
    - assets/designs/images/group-14.png
    - assets/designs/images/auto-group-id1d.png
    - assets/designs/images/hair.png
    - assets/designs/images/group-13.png
    - assets/designs/images/combined-shape-6Wt.png
    - assets/designs/images/icon-chevron-left-bda.png
    - assets/designs/images/bar-chart-fill-1.png
    - assets/designs/images/group-11-etg.png
    - assets/designs/images/home-1.png
    - assets/designs/images/background-primary-bg-h1i.png
    - assets/designs/images/image-15.png
    - assets/designs/images/image-6.png
    - assets/designs/images/users-fill-1.png
    - assets/designs/images/rectangle-16.png
    - assets/designs/images/vector-2.png
    - assets/designs/images/pants.png
    - assets/designs/images/skin.png
    - assets/designs/images/group-8.png
    - assets/designs/images/download-alt-1.png
    - assets/designs/images/auto-group-teiw.png
    - assets/designs/images/group-11-qvY.png
    - assets/designs/images/eyes.png
    - assets/designs/images/auto-group-1ssm.png
    - assets/designs/images/glasses.png
    - assets/designs/images/orange-donut-bg.png
    - assets/designs/images/lock-key-fill-1.png
    - assets/designs/images/arrow-down-bg.png
    - assets/designs/images/bar-chart-1.png
    - assets/designs/images/combined-shape-JW4.png
    - assets/designs/images/battery-1Ap.png
    - assets/designs/images/icon-chevron-down.png
    - assets/designs/images/combined-shape-w3W.png
    - assets/designs/images/color-vjz.png
    - assets/designs/images/shield-checkered-fill-1.png
    - assets/designs/images/wallet-fill.png
    - assets/designs/images/frame-21.png
    - assets/designs/images/frame-4-yZ2.png
    - assets/designs/images/home-1-sUc.png
    - assets/designs/images/auto-group-juzk.png
    - assets/designs/images/home-1-mix.png
    - assets/designs/images/image-6-zL8.png
    - assets/designs/images/battery-qYL.png
    - assets/designs/images/bar-chart-1-ANt.png
    - assets/designs/images/ring-bg.png
    - assets/designs/images/user-fill-1.png
    - assets/designs/images/pink-donut-bg.png
    - assets/designs/images/group-6-ga4.png
    - assets/designs/images/combined-shape-bSg.png
    - assets/designs/images/bg-arrow-up-bg.png
    - assets/designs/images/frame-5.png
    - assets/designs/images/cloth.png
    - assets/designs/images/vector-1.png
    - assets/designs/images/blur-behind.png
    - assets/designs/images/icon-chevron-down-ToW.png
    - assets/designs/images/group-18.png
    - assets/designs/images/arrow-up-bg.png
    - assets/designs/images/rectangle.png
    - assets/designs/images/blue-donut-bg.png
    - assets/designs/images/group-11-GHW.png
    - assets/designs/images/frame-4-VbN.png
    - assets/designs/images/group-16.png
    - assets/designs/images/icon-calendar.png
    - assets/designs/images/background-primary-bg-Aji.png
    - assets/designs/images/background-primary-bg-PH2.png
    - assets/designs/images/frame-21-3ha.png
    - assets/designs/images/lips.png
    - assets/designs/images/combined-shape-2cY.png
    - assets/designs/images/image-6-R4t.png
    - assets/designs/images/bg-dollar-bg.png
    - assets/designs/images/frame-21-Pdr.png
    - assets/designs/images/wallet-1-XYL.png
    - assets/designs/images/group-2.png
    - assets/designs/images/shadows-bg.png
    - assets/designs/images/envelope-simple-fill-1.png
    - assets/designs/images/icon-chevron-down-cMv.png
    - assets/designs/images/purple-donut-bg.png
    - assets/designs/images/rectangle-9.png
    - assets/designs/images/combined-shape-NgG.png
    - assets/designs/images/user-fill-1-EQx.png
    - assets/designs/images/background-primary-bg-YWk.png
    - assets/designs/images/combined-shape-wGU.png
    - assets/designs/images/ellipse-7.png
    - assets/designs/images/home-1-JGg.png
    - assets/designs/images/battery-oHJ.png
    - assets/designs/images/icon-chevron-left-wrG.png
    - assets/designs/images/base-bg.png
    - assets/designs/images/frame-9.png
    - assets/designs/images/bar-chart-1-Wfz.png
    - assets/designs/images/frame-21-a5W.png
    - assets/designs/images/user-1-1-qQk.png
    - assets/designs/images/cloth2.png
    - assets/designs/images/icon-chevron-left-8m6.png
    - assets/designs/images/frame-4-dSx.png
    - assets/designs/images/combined-shape-Lue.png
    - assets/designs/images/frame-21-Adn.png
    - assets/designs/images/unnamed-removebg-preview-1.png
    - assets/designs/images/icon-chevron-left-3Pv.png
    - assets/designs/images/combined-shape-2ja.png
    - assets/designs/images/group-6-Hax.png
    - assets/designs/images/wallet-fill-F1z.png
    - assets/designs/images/frame-9-pGg.png
    - assets/designs/images/group-12.png
    - assets/designs/images/user-1-1-UbS.png
    - assets/designs/images/emv-chip.png
    - assets/designs/images/wallet-fill-mKe.png
    - assets/designs/images/frame-21-Xi8.png
    - assets/designs/images/battery-HxC.png
    - assets/designs/images/image-14.png
    - assets/designs/images/emv-chip-utC.png
    - assets/designs/images/battery-kUp.png
    - assets/designs/images/specular.png
    - assets/designs/images/auto-group-qrpm.png
    - assets/designs/images/rectangle-9-Rzg.png
    - assets/designs/images/bar-chart-1-FLc.png
    - assets/designs/images/user-1-1-bap.png
    - assets/designs/images/dollar-bg.png
    - assets/designs/images/icon-chevron-left-Pjv.png
    - assets/designs/images/combined-shape-SGG.png
    - assets/designs/images/rectangle-9-t5v.png
    - assets/designs/images/group-6-Pfn.png
    - assets/designs/images/home-1-Stx.png
    - assets/designs/images/decorativeline.png
    - assets/designs/images/rectangle-9-gzC.png
    - assets/designs/images/home-1-uvx.png
    - assets/designs/images/frame-4-HYc.png
    - assets/designs/images/combined-shape-gyn.png
    - assets/designs/images/currency-circle-dollar-fill-1.png
    - assets/designs/images/wallet-fill-c64.png
    - assets/designs/images/bar-chart-1-1UC.png
    - assets/designs/images/decorativeline-vsz.png
    - assets/designs/images/check-circle-fill-1.png
    - assets/designs/images/battery-s6G.png
    - assets/designs/images/image-6-ZzQ.png
    - assets/designs/images/bg-arrow-down-bg.png
    - assets/designs/images/user-1-1-qBn.png
    - assets/designs/images/rectangle-9-u5i.png
    - assets/designs/images/combined-shape-fpt.png
    - assets/designs/images/frame-4-4Fr.png
    - assets/designs/images/rectangle-9-4y6.png
    - assets/designs/images/group-15.png
    - assets/designs/images/combined-shape-S5n.png
    - assets/designs/images/visa.png
    - assets/designs/images/background-primary-bg-gAk.png
    - assets/designs/images/image-16.png
    - assets/designs/images/icon-chevron-left-wWg.png
    - assets/designs/images/icon-chevron-left-nDn.png
    - assets/designs/images/combined-shape-cJc.png
    - assets/designs/images/bar-chart-1-nXJ.png
    - assets/designs/images/icon-chevron-up.png
    - assets/designs/images/battery-urp.png
    - assets/designs/images/user-1-1-pBr.png
    - assets/designs/images/home-1-gHv.png
    - assets/designs/images/shape.png
    - assets/designs/images/group-6-MoN.png
    - assets/designs/images/logo-paypal-1.png
    - assets/designs/images/combined-shape-JH6.png
    - assets/designs/images/wallet-fill-5ha.png
    - assets/designs/images/rectangle-9-GK2.png
    - assets/designs/images/combined-shape-EMW.png
    - assets/designs/images/group-19-VGU.png
    - assets/designs/images/rectangle-gzt.png
    - assets/designs/images/bar-chart-1-8sS.png
    - assets/designs/images/bank-fill-1.png
    - assets/designs/images/rectangle-6Kr.png
    - assets/designs/images/group-6-8TJ.png
    - assets/designs/images/group-6-iKJ.png
    - assets/designs/images/icon-chevron-left-TGt.png
    - assets/designs/images/battery-7Xv.png
    - assets/designs/images/user-1-1-FPE.png
    - assets/designs/images/combined-shape-jRi.png
    - assets/designs/images/image-5.png
    - assets/designs/images/image-5-4D6.png
    - assets/designs/images/group-19-1YC.png
    - assets/designs/images/home-1-AAC.png
    - assets/designs/images/group-6-9Rz.png
    - assets/designs/images/icon-chevron-up-FV2.png
    - assets/designs/images/image-13.png
    - assets/designs/images/group-11-QfS.png
    - assets/designs/images/rectangle-9-VB6.png
    - assets/designs/images/wallet-fill-YmN.png
    - assets/designs/images/combined-shape-rja.png
    - assets/designs/images/wallet-fill-L8x.png
    - assets/designs/images/form-bg.png
    - assets/designs/images/image-6-sWY.png
    - assets/designs/images/bar-chart-1-2bi.png
    - assets/designs/images/group-19-P9z.png
    - assets/designs/images/group-23.png
    - assets/designs/images/battery-1ui.png
    - assets/designs/images/glossy.png
    - assets/designs/images/group-6-yKn.png
    - assets/designs/images/credit-card-fill-1.png
    - assets/designs/images/rectangle-9-Z2x.png
    - assets/designs/images/group-24.png
    - assets/designs/images/user-1-1-Rax.png
    - assets/designs/images/icon-chevron-left-rNU.png
    - assets/designs/images/combined-shape-fHJ.png
    - assets/designs/images/logo-paypal-1-GnC.png
    - assets/designs/images/image-6-h68.png
    - assets/designs/images/home-1-xf2.png
    - assets/designs/images/wallet-fill-qB6.png
    - assets/designs/images/group-19-gTz.png
    - assets/designs/images/rectangle-9-VAp.png
    - assets/designs/images/combined-shape-7D2.png
    - assets/designs/images/wallet-fill-r8x.png
    - assets/designs/images/battery-25N.png
    - assets/designs/images/copy-simple-fill-1.png
    - assets/designs/images/home-1-iue.png
    - assets/designs/images/combined-shape-PLt.png
    - assets/designs/images/rectangle-9-ZXN.png
    - assets/designs/images/user-1-1-Jbz.png
    - assets/designs/images/user-1-1-46c.png
    - assets/designs/images/home-1-P2x.png
    - assets/designs/images/check-circle-fill-1-2ZW.png
    - assets/designs/images/mail.png
    - assets/designs/images/combined-shape-sBv.png
    - assets/designs/images/group-19-Cwa.png
    - assets/designs/images/group-6-58U.png
    - assets/designs/images/bar-chart-1-jZi.png
    - assets/designs/images/lock.png
    - assets/designs/images/battery-zrU.png
    - assets/designs/images/facebook-1.png
    - assets/designs/images/icon-chevron-left-xZW.png
    - assets/designs/images/pinterest-1.png
    - assets/designs/images/combined-shape-4Z6.png
    - assets/designs/images/instagram-1.png
    - assets/designs/images/icon-chevron-up-GfA.png
    - assets/designs/images/linkedin-1.png
    - assets/designs/images/icon-chevron-left-p3A.png
    - assets/designs/images/group-6-3pC.png
    - assets/designs/images/bar-chart-1-URN.png
    - assets/designs/images/google-logos-by-hrhasnai-2.png
    - assets/designs/images/rectangle-19.png
    - assets/designs/images/rectangle-18.png
    - assets/designs/images/rectangle-17.png
    - assets/thumbnail/images/screen-2.png
    - assets/designs/images/rectangle-9-N5e.png
    - assets/designs/images/rectangle-7.png
    - assets/thumbnail/images/screen-3.png
    - assets/thumbnail/images/screen-1.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
